configured_endpoints: 24
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-fc06e16064b00206b7e6ae77e52531b4f2404529444a963194ddcbac44f57970.yml
