configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-b6afad7673ca836e33a57af4efba4110c1fbd40d561bbedb20ec3a981ceeb11b.yml
