configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-e7fdaea79af67dc7150085c356b806e219f4f3af510ed017c5c5f5fa82f6eda5.yml
