configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-0bf83f9f740f045f7e68c7e659790e3108432961e3abb9d009753ba4a8df192e.yml
