configured_endpoints: 24
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-9c6261e491c3c6a40d3b91b14739d8e280dd33fb7a273b9151b5f1ecae9dc066.yml
