configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-625fac8fbd33fe4e63c32de52d45666e2eebe41ba94cadc19a07ece52c2a33f5.yml
