configured_endpoints: 24
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixpeek-esteininger%2Fmixpeek-sdk-11972738ef1acd5ca1607250dfdcc8f9adaf267f90aa4807ed97e2c77c2bfd6b.yml
